name: Docker Image CI

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"

    - name: Install neurodocker
      run: python -m pip install --editable .[dev]

    - name: version
      run: neurodocker --version

    - name: Build the Docker image
      run: docker build .
