name: Docker Image CI

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

# fedora:36, ubuntu:22.04, ubuntu:18.04, ubuntu:16.04, centos:8

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        base_image:
          [
            "fedora:36",
            "centos:8",
            "ubuntu:22.04",
            "ubuntu:18.04",
            "ubuntu:16.04",
          ]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install neurodocker
        run: python -m pip install --editable .[dev]

      - name: Generate Dockerfile
        run: |

          apt_based=("ubuntu:22.04", "ubuntu:18.04", "ubuntu:16.04")
          if [[ " ${apt_based[*]} " =~ ${{ matrix.base_image }} ]]; then
            pkg_manager="apt"
          fi

          yum_based=("fedora:36", "centos:8")
          if [[ " ${yum_based[*]} " =~ ${{ matrix.base_image }} ]]; then
            pkg_manager="yum"
          fi

          echo "pkg_manager will b:  ${pkg_manager}"

          neurodocker \
            generate docker \
            --base-image=${{ matrix.base_image }} \
            --pkg-manager=${pkg_manager} \
            --freesurfer version=7.3.1 > Dockerfile_tmp

      - name: Build the Docker image
        run: docker build -f Dockerfile_tmp .
