name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  run-tests:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python-version: ['3.11', '3.10', '3.9', '3.8']
    steps:
      - name: Install Apptainer
        env:
          VERSION=1.1.5
        run: |
          sudo apt-get update
          sudo apt-get update && apt-get install -y \
              build-essential \
              libseccomp-dev \
              pkg-config \
              uidmap \
              squashfs-tools \
              squashfuse \
              fuse2fs \
              fuse-overlayfs \
              fakeroot \
              cryptsetup \
              curl wget git
          wget -q https://github.com/apptainer/apptainer/releases/download/v${VERSION}/apptainer-${VERSION}.tar.gz && \
          tar -xzf apptainer-${VERSION}.tar.gz && \
          cd apptainer-${VERSION} && \
          ./mconfig --prefix=$HOME/opt/apptainer --without-suid && \
          make -C ./builddir && \
          sudo make -C ./builddir install
      - name: Set Apptainer/Singularity environment variables
        run: |
          echo $HOME/opt/singularity/bin >> $GITHUB_PATH
          # Give reproenv the full path to apptainer, so it still works with `sudo`.
          echo REPROENV_APPTAINER_PROGRAM=$HOME/opt/apptainer/bin/apptainer >> $GITHUB_ENV
          echo APPTAINER_CACHEDIR=/dev/shm/$(whoami)/singularity >> $GITHUB_ENV
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install neurodocker
        run: python -m pip install --editable .[dev]
      - name: Check types
        run: mypy --install-types --non-interactive neurodocker
      - name: Check style
        run: flake8 neurodocker
      - name: Run python tests
        run: pytest --numprocesses auto
      - name: Get code coverage
        run: codecov
